### ISSUE TITLE
Running a job with existing environment version but new inline definition not silently use old version

### ISSUE THREAD

**Issue by dkmiller** [Azure/azureml-previews#119]
To repro this, run a job using an inline environment definition:

**job.yml**

```yml
# yaml-language-server: $schema=https://azuremlsdk2.blob.core.windows.net/latest/commandJob.schema.json

experiment_name: azuremlv2

command: python train.py trainer.gpus=-1 +trainer.accelerator=mpi

code:
  directory: .

environment:
  name: hydra-pl
  version: 4
  conda_file: environment.yml
  docker:
    image: mcr.microsoft.com/azureml/openmpi3.1.2-cuda10.2-cudnn8-ubuntu18.04

distribution:
  type: mpi
  process_count_per_instance: 2

compute:
  target: azureml:gpu-nc12-lowpri
  node_count: 2
```

**environment.yml**

```yml
name: hydra-pl

channels:
- defaults
- conda-forge
- pytorch

dependencies:
# Sadly, AML's "canonical" Docker images only support up to CUDA 10.2.
- cudatoolkit=10.2
- pip==20.3.3
- pytorch==1.7.1
- pytorch-lightning==1.1.1
# Sadly, Python 3.8 doesn't "play nicely" with the torchvision library.
- python=3.7
- torchvision

- pip:
  - azureml-mlflow==1.19.0
  - black==20.8b1
  - hydra-core==1.0.4

```

then change the inline definition but don't change the version (e.g., update the conda spec or Docker image). The new job you submit will not show any warnings, but will **silently** use the existing environment version.

Recommended  behavior:

- (Preferred) Job submission will create a new version of the environment using the new local definition.
- (Alternative) Job submission will fail or warn on incompatible environment version + definition.

Also: bumping the version and **not** changing the definition results in a failure as well:

> (UserError) This is a duplicate of specification version 3

Also recommend that users be able to update version without changing the environment to "force" a re-build. Also &mdash; we shouldn't use "user error", see #53 .

AB#995139
