### ISSUE TITLE
YML interpolation

### ISSUE THREAD

**Issue by jpe316** [Azure/azureml-previews#140]
Support

compute:
  target: azureml:gpu-nc12-lowpri
  node_count: 2
command: python train.py trainer.num_nodes={compute.node_count}

AB#1011706

**Comment by dkmiller** [comment]
In general, hope that for any "entity" which exists in a job spec, you can refer to it:

```yaml
environment:
  name: hydra-pl

command: python foo.py {environment.name}
```

Also: want this to work in HyperDrive.
