### ISSUE TITLE
az ml environment list --name not listing versions

### ISSUE THREAD

**Issue by danielsc** [Azure/azureml-previews#182]
## Describe the issue

description: az ml environment list --name is expected to return versions, but it throws an error

## Minimal example

```
(sdk20) s-pkges:slides danielsc$ az ml environment list --name xgboost-env
unrecognized arguments: --name xgboost-env

TRY THIS:
https://aka.ms/cli_ref
Read more about the command in reference docs
```

## Additional context

-

AB#1049025

**Comment by paulshealy1** [comment]
@danielsc there are three forms of list/show:
- `az ml environment list` will list all environments. 
- `az ml environment show --name foo` will list all versions of a single environment. 
- `az ml environment show --name foo --version 1` will show a single version of an environment.

**Comment by danielsc** [comment]
Thank makes more sense
Thanks,
Daniel

**Comment by danielsc** [comment]
When I try this out, I only get the last version when running `az ml environment show --name foo`

```
(sdk20) danielscMBP:pets-resnet34 danielsc$ az ml environment show --name fastai-vision --version 1
Command group 'ml environment' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
creation_context:
  created_at: '2021-02-15T15:40:13.082923+00:00'
  created_by: Daniel Schneider
  created_by_type: User
docker:
  build:
    dockerfile: 'FROM fastdotai/fastai:latest

      RUN pip install azureml-mlflow

      '
id: azureml:/subscriptions/15ae9cb6-95c1-483d-a0e3-b1a1a3b06324/resourceGroups/ray/providers/Microsoft.MachineLearningServices/workspaces/ray/environments/fastai-vision/versions/1
name: fastai-vision
resourceGroup: ray
tags: {}
version: 1
(sdk20) danielscMBP:pets-resnet34 danielsc$ az ml environment show --name fastai-vision --version 2
Command group 'ml environment' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
creation_context:
  created_at: '2021-03-13T21:34:09.440078+00:00'
  created_by: Daniel Schneider
  created_by_type: User
docker:
  build:
    dockerfile: 'FROM fastdotai/fastai:latest

      RUN  pip install azureml-mlflow

      '
id: azureml:/subscriptions/15ae9cb6-95c1-483d-a0e3-b1a1a3b06324/resourceGroups/ray/providers/Microsoft.MachineLearningServices/workspaces/ray/environments/fastai-vision/versions/2
name: fastai-vision
resourceGroup: ray
tags: {}
version: 2
(sdk20) danielscMBP:pets-resnet34 danielsc$ az ml environment show --name fastai-vision 
Command group 'ml environment' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
creation_context:
  created_at: '2021-03-13T21:34:09.440078+00:00'
  created_by: Daniel Schneider
  created_by_type: User
docker:
  build:
    dockerfile: 'FROM fastdotai/fastai:latest

      RUN  pip install azureml-mlflow

      '
id: azureml:/subscriptions/15ae9cb6-95c1-483d-a0e3-b1a1a3b06324/resourceGroups/ray/providers/Microsoft.MachineLearningServices/workspaces/ray/environments/fastai-vision/versions/2
name: fastai-vision
resourceGroup: ray
tags: {}
version: 2
```
