### ISSUE TITLE
Error when using docker.io/daskdev/dask docker image

### ISSUE THREAD

**Issue by danielsc** [Azure/azureml-previews#183]
## Describe the issue

description:
Using the daskdev/dask docker image, I get this error:
```
AzureMLCompute job failed.
JobContainerConfigFailed: Container configuration failed unexpectedly
	JobContainerConfigFailed: Container configuration failed unexpectedly
	err: Docker exec failure when attempting to execute 'containerSetup' task. Error: exit status 1
	Reason: Docker exec failure when attempting to execute 'containerSetup' task. Error: exit status 1
	Info: Failed to prepare an environment for the job execution: Job environment preparation failed on 172.19.0.4 with err exit status 1.
```
## Minimal example
The Yaml
```yaml
# yaml-language-server: $schema=https://azuremlsdk2.blob.core.windows.net/latest/commandJob.schema.json
code: 
  directory: .
command: >-
  /bin/sh -c set
environment: 
  docker:
    image: docker.io/daskdev/dask
inputs:
  training_data:
    data: azureml:irisdata:1
    mode: mount
compute:
  target: azureml:goazurego
```

The Command
```
az ml job create --file above.yaml
```

## Additional context
- here is a run: https://ml.azure.com/experiments/id/3b32df62-b496-4f39-8498-2f08f7258493/runs/ccd1a299-8265-4f32-a21c-d1958d4fea2a?wsid=/subscriptions/15ae9cb6-95c1-483d-a0e3-b1a1a3b06324/resourcegroups/ray/workspaces/ray&tid=72f988bf-86f1-41af-91ab-2d7cd011db47#details
- this clearly works well when run locally

```
(sdk20) s-pkges:slides danielsc$ docker run -it daskdev/dask /bin/sh -c set`
+ '[' '' ']'
+ '[' -e /opt/app/environment.yml ']'
+ echo 'no environment.yml'
no environment.yml
+ '[' '' ']'
+ '[' '' ']'
+ exec /bin/sh -c set
HOME='/root'
HOSTNAME='b8a35ccd390b'
IFS=' 	
'
LANG='C.UTF-8'
LC_ALL='C.UTF-8'
OPTIND='1'
PATH='/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
PPID='1'
PS1='# '
PS2='> '
PS4='+ '
PWD='/'
SHLVL='0'
TERM='xterm'
```
