### ISSUE TITLE
_load_from_dict() missing 1 required positional argument: 'cls' for unknown YAML keys

### ISSUE THREAD

**Issue by metazool** [Azure/azureml-previews#216]
## Describe the issue

Whenever I include an unsupported key in a YAML file, I see the raw error `_load_from_dict() missing 1 required positional argument: 'cls'`

## Minimal example

With a YAML run configuration like this (note the added `test` key) 
```
experiment_name: poc
command: >-
  python train.py
environment:
  docker:
    image: mcr.microsoft.com/azureml/intelmpi2018.3-cuda10.0-cudnn7-ubuntu16.04:20210113.v1
  conda_file: file:conda_dependencies.yml
  test: 1
compute:
  target: azureml:cpu-cluster
```
And then run the job like this:
```
az ml job create --file test.yml
```

`_load_from_dict() missing 1 required positional argument: 'cls'`

## Additional context

- It would be good to see a line number and a more human readable message.
- It's around here, the raise? https://github.com/Azure/azureml-v2-preview/blob/3f37be47f6fe1db6fe9f472829f4d89b4cc243f5/sdk2-src/src/azure-ml/azure/ml/_schema/schema.py#L54 

AB#1090491
