### ISSUE TITLE
docker.io/pytorch/pytorch - gpu not used on clusters

### ISSUE THREAD

**Issue by samuel100** [Azure/azureml-previews#222]
## Describe the issue

When using the following environment:

```yaml
environment: 
  docker:
    image: docker.io/pytorch/pytorch
```

to train a CIFAR10 model on an AML compute **cluster** the GPU is not used. However, training the same model on an AML compute **instance** does use the GPU.

Running `nvidia-smi` on a compute **instance** reveals that it is using version 11.2.
Running `nvidia-smi` on a compute **cluster** reveals that is is using 10.2

## Minimal example

```
az ml job create --file jobspec.yaml
```

AB#1102205
