### ISSUE TITLE
anonymous datasets and environments are showing up in Studio and python sdk

### ISSUE THREAD

**Issue by danielsc** [Azure/azureml-previews#228]
## Describe the issue

description: anonymous datasets and environments are showing up in Studio and python sdk. They will quickly litter your workspace making it hard to find the datasets and environments you created and care for.

## Minimal example

```
az ml job create --file iris_job.yaml
```

![image](https://user-images.githubusercontent.com/8079390/112545362-6d2b8680-8db8-11eb-83d0-e64688866880.png)

![image](https://user-images.githubusercontent.com/8079390/112545427-7ddbfc80-8db8-11eb-8e33-eac415395267.png)

## Additional context
iris_job.yaml
```
# yaml-language-server: $schema=https://azuremlsdk2.blob.core.windows.net/latest/commandJob.schema.json
code:  
  local_path: train
command: >-
  python train.py 
  --data {inputs.training_data} 
environment: 
  conda_file: file:xgboost_conda.yml
  docker: 
    image: mcr.microsoft.com/azureml/intelmpi2018.3-ubuntu16.04:20210301.v1

compute:
  target: azureml:goazurego
inputs:
  training_data:
    data:
      local_path: data
    mode: mount
```

AB#1108022
