### ISSUE TITLE
Howto define independent steps?

### ISSUE THREAD

**Issue by csiebler** [Azure/azureml-previews#314]
## v2 yaml pipelines - independent steps?

preview: 0.0.83
description:

Trying to build a pipeline with 2 independent steps (see yaml below). Step 1 is training, second step is model registration. There is no need to pass data between the steps. The yaml syntax does not seem to honor that if there is no dependency between the steps, that they should run in sequence. Is there a way to define this in the yaml explicitly, e.g. using `run_after` or something?

## Additional context

Pipeline:

```yaml
name: train_register_pipeline_job
type: pipeline_job

inputs:
  training_data:
    data: azureml:mnist-tiny:1
  training_epochs: 1
  model_name: mnist-fastai-demo
  model_path: model/

defaults:
  component_job:
    compute:
      target: azureml:cpu-cluster

jobs:
  train:
    type: component_job
    component: file:../components/train.yml
    inputs:
      training_epochs: inputs.training_epochs
      training_data: inputs.training_data
  register:
    type: component_job
    component: azureml:register:1
    inputs:
      model_name: inputs.model_name
      model_path: inputs.model_path
```

Error (second steps floats lost in the graph...):

![image](https://user-images.githubusercontent.com/525867/124264911-5a51ec00-db35-11eb-8f19-a170c963434c.png)

Thanks
Clemens
