### ISSUE TITLE
Support multi-line commands in command_component

### ISSUE THREAD

**Issue by fgervais** [Azure/azureml-previews#319]
Like in regular `azure-pipelines` we can have a bash step on multiple lines like for example:

```yaml
jobs:
- job: command

  steps:
    - bash: |
        echo script line 1
        echo script line 2
```

I tried to do the same in a command_component but it got executed as a single line:

```yaml
type: command_component

name: component
display_name: component
version: 1

environment:
  docker: 
    image: docker.io/python

command: |
  pip install azure-cli
  az extension add --name ml
  az ml model list
```

```
[2021-07-14T18:09:03.879379] Starting Linux command : pip install azure-cli az extension add --name ml az ml model list

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --name
[2021-07-14T18:09:04.998289] Command finished with return code 2
```
