### ISSUE TITLE
Component environment is ignored during run

### ISSUE THREAD

**Issue by PeterFogh** [Azure/azureml-previews#323]
## Which preview? Describe the issue

**preview**: When changing the environment in the YAML the run still use an "Autosave" default environment, this my environment specification is ignored
**description**:
When creating the pipeline job I get the warning: `Warning: the provided asset name 'py38_aa_predict_app_v2_manually' will not be used for anonymous registration`. Do this mean that ignoring my custom environment is intentional? If so this should be more clear in the documentation. I suppose the documentation "Known issues (to be fixed soon...)
New environments and datasets are created each time job is submitted even when a registered environment or dataset are specified." is related to this - but then I suggest writing this alternative text "New environments (only with Python default packages) and datasets are created each time job is submitted even when a registered environment or dataset are specified, as the specified environment will be ignored."

## Additional context
Azure version
```
{
  "azure-cli": "2.27.0",
  "azure-cli-core": "2.27.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ml": "2.0.1a4"
  }
}
```

The pipeline code I use:
```
name: Pipeline_try_dask_mlflow
type: pipeline_job

inputs:
  input_o90postings: #using dataset, can use datastore + datapath also
    data: azureml:o90_postings_file_not_compressed:1
  input_int: 20
  input_float: 1.8
  input_str: 'time-based'

outputs: 
  pipeline_job_trained_model:
    data: 
      path: /output_dir

defaults:
  component_job:
    datastore: azureml:workspaceblobstore
    compute:
      target: azureml:DS12-v2

jobs:
  train-job:
    type: component_job
    component: 
      name: Train
      display_name: Train
      version: 10
      type: command_component
      inputs:
        training_data: 
          type: path
        max_epocs:
          type: integer
        learning_rate: 
          type: number
          default: 0.01
        learning_rate_schedule: 
          type: string
          default: time-based 
      outputs:
        output_folder:
          type: path
      code:
        local_path: ./
      environment:
        name: py38_aa_predict_app_v2_manually
        version: 1
        docker: 
          image: mcr.microsoft.com/azureml/base:intelmpi2018.3-ubuntu16.04
        conda_file: file:../service/predict_app/conda_env.yml
      command: >-
        python try_dask_mlflow.py
        --o90postings ${{inputs.training_data}}
        --int ${{inputs.max_epocs}}
        --float ${{inputs.learning_rate}}
        --str ${{inputs.learning_rate_schedule}}
        --output_folder ${{outputs.output_folder}}
    inputs:
      training_data: ${{inputs.input_o90postings}}
      max_epocs: ${{inputs.input_int}}
      learning_rate: ${{inputs.input_float}}
      learning_rate_schedule: ${{inputs.input_str}}
    outputs:
      output_folder: ${{outputs.pipeline_job_trained_model}}
```

**Comment by danielsc** [comment]
Hi Peter,
Could you try removing the name and version from the inline environment?
-Daniel

**Comment by PeterFogh** [comment]
If I remove "py38_aa_predict_app_v2_manually:1", thus just keeping "environment: azureml:" it results in the failure
```
Error while parsing yaml file: pipeline_try_dask_mlflow.yml 

 mapping values are not allowed here
  in "pipeline_try_dask_mlflow.yml", line 46, column 27
```
@danielsc was that what you meant?

**Comment by danielsc** [comment]
yes -- thanks
@ManojBableshwar, could you please take a look?

**Comment by danielsc** [comment]
Sorry, to be very clear, did you try this:

```yaml
name: Pipeline_try_dask_mlflow
type: pipeline_job

inputs:
  input_o90postings: #using dataset, can use datastore + datapath also
    data: azureml:o90_postings_file_not_compressed:1
  input_int: 20
  input_float: 1.8
  input_str: 'time-based'

outputs: 
  pipeline_job_trained_model:
    data: 
      path: /output_dir

defaults:
  component_job:
    datastore: azureml:workspaceblobstore
    compute:
      target: azureml:DS12-v2

jobs:
  train-job:
    type: component_job
    component: 
      name: Train
      display_name: Train
      version: 10
      type: command_component
      inputs:
        training_data: 
          type: path
        max_epocs:
          type: integer
        learning_rate: 
          type: number
          default: 0.01
        learning_rate_schedule: 
          type: string
          default: time-based 
      outputs:
        output_folder:
          type: path
      code:
        local_path: ./
      environment:
        docker: 
          image: mcr.microsoft.com/azureml/base:intelmpi2018.3-ubuntu16.04
        conda_file: file:../service/predict_app/conda_env.yml
      command: >-
        python try_dask_mlflow.py
        --o90postings ${{inputs.training_data}}
        --int ${{inputs.max_epocs}}
        --float ${{inputs.learning_rate}}
        --str ${{inputs.learning_rate_schedule}}
        --output_folder ${{outputs.output_folder}}
    inputs:
      training_data: ${{inputs.input_o90postings}}
      max_epocs: ${{inputs.input_int}}
      learning_rate: ${{inputs.input_float}}
      learning_rate_schedule: ${{inputs.input_str}}
    outputs:
      output_folder: ${{outputs.pipeline_job_trained_model}}

```

**Comment by PeterFogh** [comment]
Hi @danielsc, I have tried it now and it also results in an environment not using my conda YAML file as seen in this screenshot
![AZ-env](https://user-images.githubusercontent.com/5435299/128666498-6c1f77ff-e70e-4ea7-9dae-e8db4a8ded95.png)


```
name: Pipeline_try_dask_mlflow
type: pipeline_job

inputs:
  input_o90postings:
    data: azureml:o90_postings_file_not_compressed:1
  input_int: 20
  input_float: 1.8
  input_str: 'time-based'

outputs: 
  pipeline_job_trained_model:
    data: 
      path: /output_dir

defaults:
  component_job:
    datastore: azureml:workspaceblobstore
    compute:
      target: azureml:DS12-v2

jobs:
  train-job:
    type: component_job
    component: 
      name: try_dask_mlflow
      display_name: Try Dask and MLflow
      version: 1
      type: command_component
      inputs:
        training_data: 
          type: path
        max_epocs:
          type: integer
        learning_rate: 
          type: number
          default: 0.01
        learning_rate_schedule: 
          type: string
          default: time-based 
      outputs:
        output_folder:
          type: path
      code:
        local_path: ./
      environment:
        docker:
          image: mcr.microsoft.com/azureml/base:intelmpi2018.3-ubuntu16.04
        conda_file: file:../../service/predict_app/conda_env.yml
      command: >-
        python try_dask_mlflow.py
        --o90postings ${{inputs.training_data}}
        --int ${{inputs.max_epocs}}
        --float ${{inputs.learning_rate}}
        --str ${{inputs.learning_rate_schedule}}
        --output_folder ${{outputs.output_folder}}
    inputs:
      training_data: ${{inputs.input_o90postings}}
      max_epocs: ${{inputs.input_int}}
      learning_rate: ${{inputs.input_float}}
      learning_rate_schedule: ${{inputs.input_str}}
    outputs:
      output_folder: ${{outputs.pipeline_job_trained_model}}
```
