### ISSUE TITLE
Errors in job YAML are not surfaced clearly

### ISSUE THREAD

**Issue by dkmiller** [Azure/azureml-previews#93]
Try a simple job YAML which does not specify the environment name. The command line's error is very cryptic:

![image](https://user-images.githubusercontent.com/5003801/102286219-b2543880-3eec-11eb-8cf5-7c3450decbe9.png)

It's not clear if the **job** or **environment** needs a name from this error.

It should be more like a compiler error message, saying what is expected where.

----

```yml
code:
  directory: .

command: python src/train.py

environment:
  conda_file: environment.yml

compute:
  target: azureml:gpu-cluster
```

AB#991843
